input_dir: ./input
output_dir: /sdf/arpa/ns/q/qinzhe/html
#output_dir: ./output
google_analytics: "G-297Z25H3FE"
base_url: http://qinzhe.sdf.org
post_folder: posts
method: remote
remote_addr: "tty.sdf.org:22"
user: qinzhe
password: stdin
key_path: ''