# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: "sdf config"
    env:
      ADDR: ${{ vars.ADDR }}
      BASE_URL: ${{ vars.BASE_URL }}
      GA: ${{ vars.GA }}
      INPUT_FOLDER: ${{ vars.INPUT_FOLDER }}
      OUTPUT_FOLDER: ${{ vars.INPUT_FOLDER }}
      PORT: ${{ vars.PORT }}
      POST_FOLDER: ${{ vars.POST_FOLDER }}
      REMOTE: ${{ vars.REMOTE }}
      USER: ${{ vars.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -o gen -v generator

    - name: deploy
      run: chmod +x gen && ./gen
